# 1. Define a lambda function that takes two numbers and subtracts 1 from their sum.
{(x+y)-1}

# 2. Define a train which has the same function as the one from Question 1.
(-1++) / one of the compromises that comes with trains.

# 3. Create the array `(1 2 3;4 5 6)` with the help of the verbs you learned in the previous chapter.
#    Then, make a dictionary with the first row as keys, and the second row as values.
a:2 3#1+!6 / (1 2 3;4 5 6)
a[0]!a[1]  / makes the dictionary.

